name: Refresh proto files
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
defaults:
      run:
        working-directory: ./StabilityClient.Net/StabilityClient.Net  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 # this action allows to switch between branches
      with:
        ref: develop # the branch you want to check out
    - name: Build project
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Install dotnet grpc tools
      run: dotnet tool install -g dotnet-grpc
    - name: Restore proto files
      run: dotnet-grpc refresh
    - name: Build
      run: dotnet build --no-restore
    - name: Check for changes
      run: |
        git status --porcelain=v1 > changes.txt;
        grep -v "?? StabilityClient.Net/StabilityClient.Net/changes.txt" changes.txt > changes_filtered.txt
        echo "Error: ${{ env.error }}"
        if [ -s changes_filtered.txt ]; then
        rm -f changes.txt;
        rm -f changes_filtered.txt;
        echo "Error: ${{ env.error }}"
        echo "There are changes between master and develop branches";
        git remote add origin-develop https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/Katarzyna-Kadziolka/StabilityClient.Net.git;
        git config --global user.email "ACTION@github.com";
        git config --global user.name "GitHub Action";
        git checkout -b develop-update-$(date +"%Y-%m-%d");
        git add .;
        git commit -m "Update develop branch";
        git push -u origin-develop develop-update-$(date +"%Y-%m-%d");
        gh pr create -B develop --title "Update proto files" --body Updates;
        else
        rm -f changes.txt;
        rm -f changes_filtered.txt;
        echo "No changes between master and develop branches";
        fi;
      env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
